name: Weekly Dev to Stage PR

on:
  schedule:
    # Runs at 00:00 every Sunday
    - cron: '*/2 * * * *'

jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: develop

      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: "develop"
          destination_branch: "stage"
          github_token: ${{ secrets.Token }}
          pr_title: "Weekly merge from Develop to Stage"
          pr_body: "This is an automated pull request to update the stage branch with the latest code from develop."
          pr_reviewer: "amit992833@gmail.com,amit9928336594@gmail.com" # Reviewers' GitHub usernames
          pr_label: "automated-pr"
