name: Hello World Scheduler

on:
  schedule:
    # Runs every 2 minutes
    - cron: '*/2 * * * *'

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: echo "Hello World!"
